---
# tasks file for marathon-lb

- name: run marathon-lb container
  docker_container:
    name: marathon-lb
    image: "{{ marathon_lb_image }}"
    state: started
    detach: true
    restart_policy: always
    network_mode: host
    command: "sse --marathon {{marathon_lb_marathon_url}} --group {{marathon_lb_group}} --auth-credentials={{marathon_lb_auth_creds}}"
    env: 
      PORTS: "{{marathon_lb_ports}}"
  tags: marathon-lb

- name: register marathon-lb service in consul
  consul:
    service_name: "marathon-lb-{{marathon_lb_group}}"
    service_port: "{{marathon_lb_ports}}"
#    service_address: "{{ansible_default_ipv4.address}}"
    state: present
    http: "http://{{ansible_default_ipv4.address}}:{{marathon_lb_ports}}/_haproxy_health_check"
    interval: 10s
  tags: marathon-lb

